# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50abe323cf10bb35aaf1e7bf87d1ef6e1b329133ed18ffab56e37ff2a73b1e30eea2d2b05399b1145a45e03b1ce52e6617da07c386e720cf7b2b4c3de5e9597

test:
  secret_key_base: 41b0ecc87724186d7c2993b79780be0a1498bfe299da165144a11cdae5bf3c4cef37e32beecb3334277c3c64be37510c92ed141b31f38d1e5d0cca827921d6ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
